In [10]:
import geopandas as gpd

In [49]:
PATH_DICT = {
    "SHP_FILE": "../public/data/nhgis0001_shapefile_tl2020_us_county_2020/US_county_2020.shp", 
    "MIGRATION_FILE":  "../public/data/geo/tl2020_us_county_2020_pseudo.csv", 
    "geoData_FILE" :"../public/data/geo/tl2020_geopandas_boundary.geojson"
}

In [79]:
PATH_DICT["geoData_FILE"], PATH_DICT["MIGRATION_FILE"], PATH_DICT["SHP_FILE"]

('../public/data/geo/tl2020_geopandas_boundary.geojson',
 '../public/data/geo/tl2020_us_county_2020_pseudo.csv',
 '../public/data/nhgis0001_shapefile_tl2020_us_county_2020/US_county_2020.shp')

In [80]:
gdf = gpd.read_file( PATH_DICT["SHP_FILE"])

In [81]:
gdf.shape

(3221, 21)

In [14]:
gdf.head()

,GISJOIN,STATEFP,COUNTYFP,COUNTYNS,GEOID,NAME,NAMELSAD,LSAD,CLASSFP,MTFCC,...,CBSAFP,METDIVFP,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,Shape_Leng,Shape_Area,geometry
0,G0100010,01,001,00161526,01001,Autauga,Autauga County,06,H1,G4020,...,33860,None,A,1.539634e+09,2.567481e+07,+32.5322367,-086.6464395,210512.579904,1.565309e+09,"POLYGON ((895625.242 -524091.396, 895192.828 -..."
1,G0100030,01,003,00161527,01003,Baldwin,Baldwin County,06,H1,G4020,...,19300,None,A,4.117656e+09,1.132956e+09,+30.6592183,-087.7460666,637811.590498,4.264564e+09,"MULTIPOLYGON (((810181.191 -770353.651, 810167..."
2,G0100050,01,005,00161528,01005,Barbour,Barbour County,06,H1,G4020,...,21640,None,A,2.292160e+09,5.052321e+07,+31.8702531,-085.4051035,272036.648100,2.342684e+09,"POLYGON ((1026117.28 -548829.885, 1026126.521 ..."
3,G0100070,01,007,00161529,01007,Bibb,Bibb County,06,H1,G4020,...,13820,None,A,1.612189e+09,9.572303e+06,+33.0158929,-087.1271475,190851.068806,1.621761e+09,"POLYGON ((845023.464 -457350.174, 845421.934 -..."
4,G0100090,01,009,00161530,01009,Blount,Blount County,06,H1,G4020,...,13820,None,A,1.670259e+09,1.486028e+07,+33.9773575,-086.5664400,242282.037461,1.685119e+09,"POLYGON ((886438.269 -335474.799, 886435.536 -..."

In [22]:
gdf.query("NAME == 'Bexar'")

,GISJOIN,STATEFP,COUNTYFP,COUNTYNS,GEOID,NAME,NAMELSAD,LSAD,CLASSFP,MTFCC,...,METDIVFP,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,Shape_Leng,Shape_Area,geometry,NAMME
2538,G4800290,48,029,01383800,48029,Bexar,Bexar County,06,H1,G4020,...,None,A,3.212413e+09,40802184.0,+29.4486708,-098.5201465,284907.966228,3.253215e+09,"POLYGON ((-223805.375 -879671.469, -223805.112...",Bexar

In [23]:
gdf.columns

Index(['GISJOIN', 'STATEFP', 'COUNTYFP', 'COUNTYNS', 'GEOID', 'NAME',
       'NAMELSAD', 'LSAD', 'CLASSFP', 'MTFCC', 'CSAFP', 'CBSAFP', 'METDIVFP',
       'FUNCSTAT', 'ALAND', 'AWATER', 'INTPTLAT', 'INTPTLON', 'Shape_Leng',
       'Shape_Area', 'geometry', 'NAMME'],
      dtype='object')

In [24]:
column_dict = {
    # Pseudo migration dataset
    "year": "Year of the migration record (2018, 2019, 2020 in synthetic dataset)",
    "origin_geoid": "FIPS GEOID (state+county code) of the origin county",
    "origin_name": "Name of the origin county",
    "dest_geoid": "FIPS GEOID (state+county code) of the destination county",
    "dest_name": "Name of the destination county",
    "flow": "Simulated migration flow count (people moving from origin to destination)",

    # Shapefile metadata (from Census TIGER/Line)
    "GISJOIN": "Unique identifier (NHGIS), useful for linking to other datasets",
    "STATEFP": "State FIPS code (2-digit)",
    "COUNTYFP": "County FIPS code (3-digit)",
    "COUNTYNS": "GNIS (Geographic Names Information System) ID",
    "GEOID": "Concatenated geographic identifier (STATEFP + COUNTYFP)",
    "NAME": "County name (e.g., 'Bexar')",
    "NAMELSAD": "Name with legal/statistical area description (e.g., 'Bexar County')",
    "LSAD": "Legal/Statistical Area Description code",
    "CLASSFP": "FIPS class code (geographic type, e.g., H1 = county)",
    "MTFCC": "Census feature classification code (e.g., G4020 = county)",
    "CSAFP": "Combined Statistical Area FIPS code",
    "CBSAFP": "Core Based Statistical Area FIPS code (metro/micro area)",
    "METDIVFP": "Metropolitan Division code (for large metros)",
    "FUNCSTAT": "Functional status (A = active, I = inactive)",
    "ALAND": "Land area (square meters)",
    "AWATER": "Water area (square meters)",
    "INTPTLAT": "Latitude of internal point (centroid)",
    "INTPTLON": "Longitude of internal point (centroid)",
    "Shape_Leng": "Polygon perimeter length (projection-dependent)",
    "Shape_Area": "Polygon area (projection-dependent)",
    "geometry": "Geometry (polygon) of the county boundary",
    "NAMME": "Extra name/label column (sometimes duplicate of NAME or localized)"
}

In [ ]:
COLS_CHECK = ["COUNTYFP", "STATEFP" , "COUNTYNS", "GEOID", "NAME", "NAMELSAD", "GEOID"]
[f"The unique values for column {col}: {gdf[col].nunique()}"
            for col in  COLS_CHECK
]

['The unique values for column COUNTYFP: 326',
 'The unique values for column STATEFP: 52',
 'The unique values for column COUNTYNS: 3221',
 'The unique values for column GEOID: 3221',
 'The unique values for column NAME: 1911',
 'The unique values for column NAMELSAD: 1956',
 'The unique values for column GEOID: 3221']

In [64]:
counties_gdf = gdf[["GEOID", "NAME", "NAMELSAD", "geometry", "STATEFP"]]
counties_gdf.head()

,GEOID,NAME,NAMELSAD,geometry,STATEFP
0,01001,Autauga,Autauga County,"POLYGON ((895625.242 -524091.396, 895192.828 -...",01
1,01003,Baldwin,Baldwin County,"MULTIPOLYGON (((810181.191 -770353.651, 810167...",01
2,01005,Barbour,Barbour County,"POLYGON ((1026117.28 -548829.885, 1026126.521 ...",01
3,01007,Bibb,Bibb County,"POLYGON ((845023.464 -457350.174, 845421.934 -...",01
4,01009,Blount,Blount County,"POLYGON ((886438.269 -335474.799, 886435.536 -...",01

In [69]:
import geopandas as gpd
import pandas as pd
import numpy as np

# # 1. Load real county shapefile (Census TIGER/Line)
# url = "https://www2.census.gov/geo/tiger/TIGER2022/COUNTY/tl_2022_us_county.zip"
# counties_gdf = gpd.read_file(url)[["GEOID", "NAMELSAD", "STATEFP"]]

# 2. Select 10 counties per state

selected = (
    counties_gdf.groupby("STATEFP")
    .apply(lambda x: x.sample(min(10, len(x)), random_state=42), include_groups=False)
    .reset_index(drop=True)
)

# 3. Generate migration flows (GEOIDs only)
years = [2018, 2019, 2020]
records = []
np.random.seed(42)

for _, row in selected.iterrows():
    for y in years:
        n_flows = np.random.randint(2, 6)
        for _ in range(n_flows):
            dest = selected.sample(1).iloc[0]
            while dest["GEOID"] == row["GEOID"]:
                dest = selected.sample(1).iloc[0]

            if np.random.rand() > 0.5:
                origin_geoid, dest_geoid = row["GEOID"], dest["GEOID"]
            else:
                origin_geoid, dest_geoid = dest["GEOID"], row["GEOID"]

            flow_count = np.random.randint(10, 1001)
            records.append({"year": y,
                            "origin_geoid": origin_geoid,
                            "dest_geoid": dest_geoid,
                            "flow": flow_count})

migration_df = pd.DataFrame(records)

# 4. Attach *real county names*
migration_df = migration_df.merge(
    counties_gdf[["GEOID", "NAMELSAD"]],
    left_on="origin_geoid", right_on="GEOID",
    how="left"
).rename(columns={"NAMELSAD": "origin_name"}).drop(columns=["GEOID"])

migration_df = migration_df.merge(
    counties_gdf[["GEOID", "NAMELSAD"]],
    left_on="dest_geoid", right_on="GEOID",
    how="left"
).rename(columns={"NAMELSAD": "dest_name"}).drop(columns=["GEOID"])

In [70]:
migration_df.head()

   year origin_geoid dest_geoid  flow          origin_name         dest_name
0  2018        01073      54065   617     Jefferson County     Morgan County
1  2018        01073      26045   845     Jefferson County      Eaton County
2  2018        38011      01073   197        Bowman County  Jefferson County
3  2018        22123      01073   846  West Carroll Parish  Jefferson County
4  2019        72153      01073    89      Yauco Municipio  Jefferson County

In [71]:
# Calculate net migration = inflow - outflow per county per year

# Inflow: sum of flows where county is destination
inflow = (
    migration_df.groupby(["year", "dest_geoid"])["flow"]
    .sum()
    .reset_index()
    .rename(columns={"dest_geoid": "GEOID", "flow": "inflow"})
)

# Outflow: sum of flows where county is origin
outflow = (
    migration_df.groupby(["year", "origin_geoid"])["flow"]
    .sum()
    .reset_index()
    .rename(columns={"origin_geoid": "GEOID", "flow": "outflow"})
)

# Merge inflow and outflow
net_mig = pd.merge(inflow, outflow, on=["year", "GEOID"], how="outer").fillna(0)

# Calculate net migration
net_mig["net_migration"] = net_mig["inflow"] - net_mig["outflow"]

In [72]:
net_mig.head(20)

    year  GEOID  inflow  outflow  net_migration
0   2018  01009   878.0   1725.0         -847.0
1   2018  01011  3731.0    196.0         3535.0
2   2018  01019  2359.0   1567.0          792.0
3   2018  01025  2154.0    314.0         1840.0
4   2018  01033  1362.0   1952.0         -590.0
5   2018  01073  3765.0   2234.0         1531.0
6   2018  01081  1691.0    535.0         1156.0
7   2018  01091   105.0   5844.0        -5739.0
8   2018  01123  2722.0    682.0         2040.0
9   2018  01129  2420.0    736.0         1684.0
10  2018  02013  1551.0   1766.0         -215.0
11  2018  02070  1333.0    719.0          614.0
12  2018  02090  1307.0   2410.0        -1103.0
13  2018  02110   554.0    457.0           97.0
14  2018  02150  1723.0   2679.0         -956.0
15  2018  02164  1846.0   1790.0           56.0
16  2018  02198   855.0   1538.0         -683.0
17  2018  02220  1090.0   3276.0        -2186.0
18  2018  02275   326.0    573.0         -247.0
19  2018  02282  2460.0   1096.0         1364.0

In [51]:
gdf[["GEOID", "NAME", "geometry"]].to_file(PATH_DICT["geoData_FILE"], driver="GeoJSON")

In [73]:
migration_df.to_csv(PATH_DICT["MIGRATION_FILE"], index=False)

In [75]:
migration_df.head()

   year origin_geoid dest_geoid  flow          origin_name         dest_name
0  2018        01073      54065   617     Jefferson County     Morgan County
1  2018        01073      26045   845     Jefferson County      Eaton County
2  2018        38011      01073   197        Bowman County  Jefferson County
3  2018        22123      01073   846  West Carroll Parish  Jefferson County
4  2019        72153      01073    89      Yauco Municipio  Jefferson County

In [ ]:
# check the size per year
migration_df.groupby("year").size()

year
2018    1718
2019    1710
2020    1719
dtype: int64

In [ ]:
# Save separate CSV files for each year's flow data

for year, group in migration_df.groupby('year'):
    group.to_csv(f'../public/data/flow/flow_{year}.csv', index=False)